### ISSUE TITLE
ssast pretrained solely on Audioset-2M

### ISSUE THREAD

**Issue by Moadab-AI** [YuanGongND/ssast#1]
In the paper there is a section where you compare the model trained self-supervised only on Audioset-2M to the default model where you combine it with librispeech. Could you please kindly share the self-supervised pretrained model on Audioset-2M alone?

Thanks in advance.

**Comment by YuanGongND** [comment]
Thanks.

I will need some time to check where the model is on our server and convert it to the release version (the model definition is simplified in the released version). I will keep you posted.

Best,
Yuan

**Comment by YuanGongND** [comment]
Ok, I add all models in Table 2 of the paper. Please check the readme file again. 

-Yuan
